# Generated by Django 4.1.3 on 2023-02-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField(max_length=12)),
                ('age', models.IntegerField(max_length=2)),
                ('isActive', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
    ]
