# Generated by Django 4.1.3 on 2023-02-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('contact', models.IntegerField()),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('address', models.CharField(max_length=200)),
                ('working', models.BooleanField(default=True)),
                ('department', models.CharField(max_length=20)),
            ],
        ),
    ]
