# Generated by Django 4.1.3 on 2023-02-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_data',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
