# Generated by Django 4.1.3 on 2023-02-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(verbose_name=6)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(default='amardiep@xyz.com', max_length=200)),
                ('phone', models.IntegerField(verbose_name=12)),
                ('sex', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
    ]
