# Generated by Django 4.1.3 on 2023-02-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_rename_emp_id_dbs_wid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dbs',
            new_name='worker',
        ),
    ]
