# Generated by Django 4.1.3 on 2023-02-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_rename_dbs_worker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='worker',
            new_name='addworker',
        ),
    ]
