# Generated by Django 4.1.3 on 2023-02-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0004_rename_worker_addworker'),
    ]

    operations = [
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.IntegerField(verbose_name=6)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(default='amardiep@xyz.com', max_length=200)),
                ('phone', models.IntegerField(verbose_name=12)),
                ('sex', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
    ]
