# Generated by Django 4.1.3 on 2023-02-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0005_worker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='worker',
        ),
    ]
